import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RecipeDataProvider } from "./context/RecipeDataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="grid content-between min-h-[100vh]">
          <RecipeDataProvider>{children}</RecipeDataProvider>

          <footer className="bg-fuchsia-950/50 mt-10">
            <div className="flex justify-center text-sm p-6">
              🌸Done By Iryna Lysko🌸
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
